"""empty message

Revision ID: f7036e9d60d7
Revises: 032244060c7b
Create Date: 2021-01-02 13:54:25.012030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7036e9d60d7'
down_revision = '032244060c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('Show', 'shows')
    op.rename_table('Venue', 'venues')
    op.rename_table('Artist', 'artists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('shows', 'Show')
    op.rename_table('venues', 'Venue')
    op.rename_table('artists', 'Artist')
    # ### end Alembic commands ###
